# Generated by Django 5.1.15 on 2026-09-19 19:47

from django.db import migrations, models


def seed_gateways(apps, schema_editor):
    """BROZIDO defaults: Razorpay enabled and primary, PayU present but disabled."""
    PaymentGatewayConfig = apps.get_model("payments", "PaymentGatewayConfig")
    PaymentGatewayConfig.objects.get_or_create(gateway="razorpay", defaults={"is_enabled": True, "is_primary": True})
    PaymentGatewayConfig.objects.get_or_create(gateway="payu", defaults={"is_enabled": False, "is_primary": False})


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_transaction_attempted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGatewayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[("razorpay", "Razorpay"), ("payu", "PayU")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Offer this gateway at checkout. Requires its credentials to be configured.",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="The default gateway, listed first at checkout. Exactly one enabled gateway is primary.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment gateway",
                "verbose_name_plural": "Payment gateways",
            },
        ),
        migrations.RunPython(seed_gateways, migrations.RunPython.noop),
    ]
