# Generated by Django 5.1.15 on 2026-09-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_sitesettings_charge_for_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("is_enabled", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Feature flag",
                "verbose_name_plural": "Feature flags",
                "ordering": ["key"],
            },
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="BROZIDO", max_length=120),
        ),
    ]
