# Generated by Django 5.1.15 on 2026-09-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_brozido_site_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="cod_disabled_pincodes",
            field=models.TextField(
                blank=True,
                help_text="One pincode per line, or a leading part followed by * to block a whole area (e.g. 6820* blocks every pincode starting 6820).",
                verbose_name="COD unavailable at these pincodes",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cod_disabled_states",
            field=models.TextField(
                blank=True,
                help_text="One state name per line (e.g. Kerala). COD is hidden for delivery addresses in these states.",
                verbose_name="COD unavailable in these states",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cod_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Offer Cash on Delivery at checkout. Turn off to disable COD everywhere.",
                verbose_name="Cash on delivery enabled",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="active_payment_gateway",
            field=models.CharField(
                choices=[("razorpay", "Razorpay"), ("payu", "PayU")],
                default="razorpay",
                help_text="No longer used. Gateway availability is managed under Payments -> Payment gateways.",
                max_length=20,
                verbose_name="Active Payment Gateway (deprecated)",
            ),
        ),
    ]
