# Generated by Django 5.1.15 on 2026-09-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0014_place_secondary_banner_after_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslide",
            name="link_url",
            field=models.CharField(
                blank=True,
                help_text="Where the 'Shop Now' button (and the slide itself) goes when tapped. A path on this site (e.g. /shop/category/hoodies/) or a full https:// address. Leave blank to link to the shop page.",
                max_length=500,
                verbose_name="Link URL",
            ),
        ),
        migrations.AddField(
            model_name="secondaryslide",
            name="link_url",
            field=models.CharField(
                blank=True,
                help_text="Where this banner card goes when tapped. A path on this site (e.g. /shop/category/hoodies/) or a full https:// address. Leave blank to link to the shop page.",
                max_length=500,
                verbose_name="Link URL",
            ),
        ),
    ]
